In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split


In [3]:
data = pd.read_csv('C:\\Users\\asd\\Desktop\\Winter Training\\data1.csv', header=None)
print(data)
labels=pd.read_csv('C:\\Users\\asd\\Desktop\\Winter Training\\label1.csv',header=None)
print(labels)

             0         1         2         3         4         5         6   \
0     -0.446891 -0.013397  0.232645  2.156649  1.652923 -0.210531 -0.662227   
1      0.243747 -1.144175 -0.622214 -0.661979 -0.373315  0.520313 -1.307954   
2     -1.417799 -0.088833 -0.647181 -1.141497 -1.321100  0.686798 -1.045569   
3      0.656784  0.381201 -1.039011  1.285315  0.808324  1.428519 -1.144367   
4      1.098520  1.706769 -1.030370  2.001009  2.751551  1.202229 -0.941066   
5     -0.035569  1.481734  1.693223  1.437399  0.822527 -1.344757 -2.833138   
6     -0.458196  1.103694 -0.985771  0.038616  0.510555 -0.036480  2.104910   
7      0.009687  0.695721 -1.295533  0.609140 -0.484269  0.083173 -1.850543   
8      0.711168  0.642080 -0.809361  1.377562  1.364644  0.662236 -1.127384   
9     -0.026433  0.536858  0.809480  0.883268  0.631330 -0.834701  0.292860   
10    -0.205401  0.450749 -0.495106  0.314523  1.854108  0.604280 -0.703304   
11     0.537284 -0.354807 -1.852824  1.767041  1.117

In [4]:
npData=np.asarray(data)
npLabels=np.asarray(labels)
print(npData.shape)
print(npLabels.shape)

(20000, 20)
(20000, 1)


In [5]:
print(np.max(npLabels))
print(np.min(npLabels))

4
0


In [6]:
np.unique(npLabels)

array([0, 1, 2, 3, 4], dtype=int64)

In [7]:
num=np.max(npLabels)+1
oneHot=np.eye(num)[npLabels]
print(oneHot.ndim)
print(oneHot.shape)

3
(20000, 1, 5)


In [8]:
oneHotRe=np.reshape(oneHot, [20000,5])
print(oneHotRe)

[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 ..., 
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.]]


In [9]:
trainData,testDataDash=train_test_split(npData,train_size=0.8,test_size=0.2,shuffle=False)
trainLabel,testLabelDash=train_test_split(oneHotRe,train_size=0.8,test_size=0.2,shuffle=False)

In [10]:
validData,testData=train_test_split(testDataDash,train_size=0.5,test_size=0.5,shuffle=False)
validLabel,testLabel=train_test_split(testLabelDash,train_size=0.5,test_size=0.5,shuffle=False)

In [11]:
h=int(input())#Number of neurons in the hidden layer

20


In [12]:
b1=np.zeros(h)
b2=np.zeros(5)
print(b1)
print(b2)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.]
[ 0.  0.  0.  0.  0.]


In [13]:
w1=np.random.normal(0, 1/np.sqrt(20), (20,h))
w2=np.random.normal(0, 1/np.sqrt(h), (h,5))

In [23]:
def actFunc(huehue,choice):
    #tanh
    if(choice==1):
        return np.tanh(huehue)
    elif(choice==2):
        temp=np.exp(huehue)
        return temp/np.sum(temp,axis=1,keepdims=True)

In [1]:
alpha = float(input()) #learning rate

0.003


In [15]:
batch=int(input())

1000


In [16]:
def costFunc(y,t):
    return -(t*(np.log(y))+(1-t)*np.log(1-y))

In [17]:
def forwFunc(data):
    a0=data
    z1=np.dot(a0,w1)+b1
    a1=ActFunc(z1,1)
    z2=np.dot(a1,w2)+b2
    a2=ActFunc(z2,2)
    return a0,z1,a1,z2,a2

In [18]:
def Acc(y,t,size):
    maxData=np.argmax(y,axis=1)
    maxLabel=np.argmax(t,axis=1)
    compare=np.equal(maxData,maxLabel)
    count=np.sum(compare)
    return (count/size)*100

In [19]:
epochs=int(input("epochs"))

epochs100


In [28]:
for epoch in range(epochs):
    for iteration in range(int(len(trainData)/batch)):
        a0,z1,a1,z2,a2=forwFunc(trainData[iteration*batch:(iteration+1)*batch,:])
        y=a2
        labelBatch=trainLabel[iteration*batch:(iteration+1)*batch,:]
        del2=(y-labelBatch)
        del1=np.dot(del2,w2.T)*(1-pow(actFunc(z1,1),2))
        dcdw2=np.dot(a1.T,del2)
        dcdw1=np.dot(a0.T,del1)
        dcdb1=np.sum(del1,axis=0)
        dcdb2=np.sum(del2,axis=0)
        w1=w1-alpha*dcdw1
        w2=w2-alpha*dcdw2
        b2=b2-alpha*dcdb2
        b1=b1-alpha*dcdb1
    a0,z1,a1,z2,a2=forwFunc(trainData)
    print("Training Cost",(np.sum(costFunc(a2,trainLabel)))/16000.0)
    print("Training accuracy",Acc(a2,trainLabel,len(trainLabel)))

Training Cost 0.858215972097
Training accuracy 82.21875
Training Cost 0.792296599463
Training accuracy 84.25625
Training Cost 0.751948802759
Training accuracy 85.325
Training Cost 0.713926627014
Training accuracy 86.08125
Training Cost 0.678456142742
Training accuracy 86.7
Training Cost 0.643325694733
Training accuracy 87.41875
Training Cost 0.611726280281
Training accuracy 87.96875
Training Cost 0.589149961747
Training accuracy 88.33125
Training Cost 0.573725007378
Training accuracy 88.675
Training Cost 0.556589227219
Training accuracy 89.1625
Training Cost 0.540892583892
Training accuracy 89.56875
Training Cost 0.525565219665
Training accuracy 90.13125
Training Cost 0.518333248565
Training accuracy 90.4875
Training Cost 0.558455335844
Training accuracy 89.6125
Training Cost 0.516390934632
Training accuracy 90.5125
Training Cost 0.508927241299
Training accuracy 90.65625
Training Cost 0.506988010411
Training accuracy 90.675
Training Cost 0.506504235021
Training accuracy 90.7625
Trainin