#### Importing the libraries

In [25]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

#### Reading the data

In [26]:
data=pd.read_csv('C:/Users/asd/Desktop/Winter Training/data1.csv',header=None)

#### Then we convert the data into numpy arrays

In [27]:
npData=np.asarray(data)
print npData

[[-0.44689111 -0.01339702  0.23264493 ..., -0.94587809  1.84092189
  -0.27902404]
 [ 0.24374694 -1.14417545 -0.62221358 ...,  0.90293107 -1.41872787
  -0.29013935]
 [-1.41779879 -0.0888327  -0.647181   ...,  1.20946469 -1.52638614
   0.33777109]
 ..., 
 [-0.80040466  1.47799654  0.0900574  ...,  0.37866958  0.11096771
  -0.17636265]
 [-1.21734449 -0.78540102 -0.41378073 ...,  0.24927734 -0.94149613
   1.66166061]
 [ 1.60100517 -0.89039824 -1.42504908 ..., -0.02377265  1.2208092
   1.48933029]]


#### Printing the dimensions, size and shape of the array of data. npData represents the whole data array of 20000X20 dimensions

In [28]:
print npData.ndim
print npData.size
print npData.shape

2
400000
(20000L, 20L)


### The shape here says that there are 20000 datapoints or inputs we can give to the neural network

### 20 here suggests that there are 20 different feutures of the data which we are studying and hence signifies the number of input neurons

##### Doing the same for labels.csv and saving the array of corresponding labels of the data 20000X1 into a numpy array 

In [29]:
label=pd.read_csv('C:/Users/asd/Desktop/Winter Training/label1.csv',header=None)

In [30]:
npLabel=np.asarray(label)
print npLabel

[[3]
 [2]
 [2]
 ..., 
 [2]
 [2]
 [0]]


In [31]:
print npLabel.ndim
print npLabel.size
print npLabel.shape

2
20000
(20000L, 1L)


#### Then we convert our labels in the one hot format where we convert each labelinto a matrix so that all numbers in the label can be clasified individually

In [32]:
n_values = np.max(npLabel) + 1
oneHotDash=np.eye(n_values)[npLabel]
oneHot=np.reshape(oneHotDash,(20000,5))##we reshape from a 3D matrix as built by default using eye function to a 2D array
print oneHot
print oneHot.shape

[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 ..., 
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.]]
(20000L, 5L)


In [33]:
trainData,testDataDash=train_test_split(npData,train_size=0.8,test_size=0.2,shuffle=False)#divide data in a 80:20 ratio
trainLabel,testLabelDash=train_test_split(oneHot,train_size=0.8,test_size=0.2,shuffle=False)
print trainData.shape
print testDataDash.shape
print trainLabel.shape
print trainLabel
print testLabelDash.shape

(16000L, 20L)
(4000L, 20L)
(16000L, 5L)
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 ..., 
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.]]
(4000L, 5L)


In [34]:
validateData, testData=train_test_split(testDataDash,train_size=0.5,test_size=0.5,shuffle=False)#dividing rest20% data half half in validation and testing data
validateLabel, testLabel=train_test_split(testLabelDash,train_size=0.5,test_size=0.5,shuffle=False)
print validateData.shape
print testData.shape
print validateLabel.shape
print testLabel.shape


(2000L, 20L)
(2000L, 20L)
(2000L, 5L)
(2000L, 5L)


### There are 20 neurons in the input layer.

### There are 5 neurons in the output layer

### There are 10 neurons in the hidden layer

#### Here we take input of the number of neurons in the hidden layer of our single layered neural network

In [1]:
h=input()#number of neurons in the hidden layer

10


#### Biases are initialized to be zero

In [35]:
b1=np.zeros(h)
b2=np.zeros(5)
print b1
print b2

[ 0.  0.  0. ...,  0.  0.  0.]
[ 0.  0.  0.  0.  0.]


#### We make randomized weight matricesaccording to random normal distribution which is according to 0 mean and 1/nL variance or1/sqrt(nL) standard deviation where nL if the number of inuts to that particular layer 

In [36]:
std1=(1/np.sqrt(20))#standard deviation of initialiing first weights
std2=(1/np.sqrt(h))#standard deviation of initialiing second weights
print std1,std2
w1=np.random.normal(0,std1,(20,h))#gaussian random assignment of weight
print w1
print''
w2=np.random.normal(0,std2,(h,5))#gaussian random assignment of weights 
print w2
print w1.shape
print w2.shape


0.22360679775 0.03125
[[-0.04500349 -0.30626745  0.46046042 ..., -0.27906925  0.0710719
   0.18238645]
 [ 0.09609046  0.1882918   0.40261746 ...,  0.10857276  0.06954503
   0.04317422]
 [-0.07735335  0.20140305  0.2416908  ...,  0.28440318 -0.01812375
  -0.24110837]
 ..., 
 [ 0.07977438 -0.17601851 -0.23602727 ..., -0.1316114   0.33085649
   0.20932723]
 [-0.00600366  0.17764019  0.0464903  ...,  0.09134482  0.33533739
   0.19153143]
 [-0.20104192 -0.32797319 -0.01290107 ...,  0.22132287  0.03630171
  -0.15123682]]

[[-0.00287981 -0.01793399 -0.01191854 -0.01831779 -0.01688113]
 [-0.03880488  0.00818628  0.01344801 -0.00275655  0.02041775]
 [-0.00659054  0.01696337  0.01073463  0.00408753  0.05804079]
 ..., 
 [-0.05677376 -0.02745974  0.02481959 -0.07135361 -0.01040379]
 [ 0.02893276  0.01016503 -0.04219277  0.05354089 -0.02215447]
 [-0.00203969 -0.01804712 -0.00365559 -0.01449677 -0.01772363]]
(20L, 1024L)
(1024L, 5L)


#### Here we make a function which takes in two parameters, haha is any matrix of mXn shape and choose is an integer variable which takes input of which type of activation do we want to use

In [37]:
def actFunc(haha,choose):
    if choose==1:#Sigmoid
        return (1/(1+np.exp(haha)))
    elif choose==2:#ReLU
        return np.max(0,haha)
    elif choose==3:#tanh
        return np.tanh(haha)
    elif choose==4:#softmax
        temp=np.exp(haha)
        return temp/np.sum(temp,axis=1,keepdims=True)

## Enter the Learning Rate

In [16]:
alpha = input()

0.001


## Enter the size of the mini batch

When batch size = 1, we are doing a stochastic approach of neural network which takes one datapoint at a time and adjust weight according to each one of them. The learning process is the slowest in stochastic as well as a very high accuracy is found out. Also, it requires much more processing power due to continuous forward and backward passes.

When batch size is equal to the whole dataset's size, we say that we have approached with a full batch approach. Here, we take the whole data at once, apply a forward pass on it, calculate the gradient descent(it gives a single line to the minima), and do the backward pass and hence update the weights and biases(parameters). This has the fastest learning rate and learns very good. However, with larger datasets, chances are that we might not be able to use them as arrays in our controllers. Hence, we use a trade-off between stochastic and full batch which is known as the mini batch process

When batch size is more than one and is less than the total number of data points, we are doing a mini batch approach wherein, we take a chunk of the whole data, say 1000 of 16000 images, at a time, do a forward pass on this chunk of data, compute the gradient and do a backward pass to adjust the weights and biases(parameters) according to these 1000 data points. This completes one iteration. Then, we take the next chunk of data with the same batch size ad repeat the same process. Hence, when we complete this on our complete dataset, we say that we have completed one epoch

In [38]:
batch=input()

1000


# Neural Network Implementation

### Cost Function

In [39]:
def costFunc(y,t):
    return -(t*(np.log(y))+(1-t)*np.log(1-y))

### Feed Forward Function`

In [40]:
def forwardFunc(Data):
    a0=Data
    z1=np.dot(a0,w1)+b1
    a1=actFunc(z1,3)
    z2=np.dot(a1,w2)+b2
    a2=actFunc(z2,4)
    return a0,z1,a1,z2,a2

### Accuracy Function

In [41]:
def accuracyFunc(output,labelData,dataSize):
    maxInRow=np.argmax(output, axis=1)
    maxInLabels=np.argmax(labelData, axis=1)
    huehue=np.equal(maxInRow,maxInLabels)
    count=np.sum(huehue)
    #count=0
    #for l in range(16000):
    #    if maxInRow[l]==maxInLabels[l]:
    #        count=count+1
    return (count/dataSize)*100

In [47]:
print(trainData[0])
print(trainLabel[0])

[-0.44689111 -0.01339702  0.23264493  2.15664884  1.65292329 -0.21053079
 -0.66222709  0.70514395  1.43468372 -0.4457503  -0.17850107 -0.90550337
 -0.59409921 -0.7285856  -0.62700244 -0.24051958  0.13169638 -0.94587809
  1.84092189 -0.27902404]
[ 0.  0.  0.  1.  0.]


In [51]:
trainLabel[i*batch:(i+1)*batch,:].shape

(1000L, 5L)

In [50]:
y.shape

(1000L, 5L)

## Artificial Neural Network


In [22]:
for j in range (100):
    #one epoch
    for i in range(trainData.shape[0]/batch):#for each iteration, we use a for loop.
        a0,z1,a1,z2,a2=forwardFunc(trainData[i*batch:(i+1)*batch,:])
        y=a2
        labelBatch=trainLabel[i*batch:(i+1)*batch,:]
        #Backward pass
        del2=(y-labelBatch)
        del1=np.dot(del2,w2.T)*(1-pow(actFunc(z1,3),2))
        dcdw2=np.dot(a1.T,del2)
        dcdw1=np.dot(a0.T,del1)
        dcdb1=np.sum(del1,axis=0)
        dcdb2=np.sum(del2,axis=0)
        w1=w1-alpha*dcdw1
        w2=w2-alpha*dcdw2
        b2=b2-alpha*dcdb2
        b1=b1-alpha*dcdb1
    #Cost after one epoch
    a0,z1,a1,z2,a2=forwardFunc(trainData)
    ytrue=a2
    cost=np.sum(costFunc(ytrue,trainLabel))/16000
    print "cost"
    print cost
    accuracy = accuracyFunc(ytrue,trainLabel,16000.0)
    print "training accuracy"
    print accuracy
##validation
va0,vz1,va1,vz2,va2=forwardFunc(validateData)
vOutput=va2
accuracy = accuracyFunc(vOutput,validateLabel,2000.0)
print "validation accuracy"
print accuracy

cost
3.81827343515
training accuracy
60.21875
cost
2.40222174611
training accuracy
65.18125
cost
1.55049415451
training accuracy
70.23125
cost
1.63501759004
training accuracy
71.85625
cost
1.11134256805
training accuracy
78.75625
cost
1.10641824391
training accuracy
78.05625
cost
0.95758495661
training accuracy
81.0625
cost
0.968170985638
training accuracy
81.95
cost
0.788847322109
training accuracy
85.2375
cost
0.786331954738
training accuracy
85.29375
cost
0.731581371861
training accuracy
86.21875
cost
0.750164336519
training accuracy
85.375
cost
0.736396778174
training accuracy
85.7
cost
0.673129929402
training accuracy
87.40625
cost
0.646193876852
training accuracy
87.91875
cost
0.626979191083
training accuracy
88.25
cost
0.599228242014
training accuracy
88.7875
cost
0.692662828654
training accuracy
86.36875
cost
0.623715356508
training accuracy
87.9625
cost
0.585827894922
training accuracy
89.0
cost
0.576307250258
training accuracy
89.3875
cost
0.55405373582
training accuracy
89.7