In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[    0.0000,     0.0000,     0.0000],
        [    0.0000,     0.0000,     0.0000],
        [-3253.9375,     0.0000,     0.0000],
        [    0.0000,     0.0000,     0.0000],
        [-3239.1875,     0.0000,     0.0000]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.8458,  0.2086,  0.2695],
        [ 0.5959,  0.5029,  0.8919],
        [ 0.7379,  0.3658,  0.3037],
        [ 0.2542,  0.5276,  0.3779],
        [ 0.2441,  0.3186,  0.9973]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.7490,  0.9866,  1.7303],
        [-0.6260, -2.7901,  0.1585],
        [-1.0703, -0.8626, -0.0550],
        [ 0.7234,  0.9106,  0.4309],
        [-0.6638,  0.4315, -0.6205]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.0744,  1.8248,  2.6829],
        [-0.3296, -1.8147,  1.0769],
        [-0.3636, -0.5605,  0.7066],
        [ 0.8537,  1.0381,  0.8990],
        [-0.0411,  0.7128, -0.3985]])


In [12]:
print(torch.add(x, y))

tensor([[ 1.0744,  1.8248,  2.6829],
        [-0.3296, -1.8147,  1.0769],
        [-0.3636, -0.5605,  0.7066],
        [ 0.8537,  1.0381,  0.8990],
        [-0.0411,  0.7128, -0.3985]])


In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.0744,  1.8248,  2.6829],
        [-0.3296, -1.8147,  1.0769],
        [-0.3636, -0.5605,  0.7066],
        [ 0.8537,  1.0381,  0.8990],
        [-0.0411,  0.7128, -0.3985]])


In [14]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.0744,  1.8248,  2.6829],
        [-0.3296, -1.8147,  1.0769],
        [-0.3636, -0.5605,  0.7066],
        [ 0.8537,  1.0381,  0.8990],
        [-0.0411,  0.7128, -0.3985]])


In [16]:
print(x)
print(x[:, 1])

tensor([[ 0.7490,  0.9866,  1.7303],
        [-0.6260, -2.7901,  0.1585],
        [-1.0703, -0.8626, -0.0550],
        [ 0.7234,  0.9106,  0.4309],
        [-0.6638,  0.4315, -0.6205]])
tensor([ 0.9866, -2.7901, -0.8626,  0.9106,  0.4315])


In [ ]:
x = torch.randn(4, 4) #A random 

y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())